### ISSUE TITLE
where is the post_process?

### ISSUE THREAD

**Issue by liushuchun** [XinJCheng/CSPN#1]

**Comment by ZhangC2** [comment]
I think the CSPN.py  is post_process file @liushuchun

**Comment by XinJCheng** [comment]
CSPN.py is the code that implements the cspn module proposed in this paper. Actually, there is no need for explicit post processing, we just learned the affinity matrix from the shared network for our main job, then feed the affinity matrix and blur depth to our cspn module to get the final results.
