### ISSUE TITLE
Whether this is mistake 

### ISSUE THREAD

**Issue by sunlibocs** [XinJCheng/CSPN#18]
Hi Xinjin,
**We can see that guidance can get 12 channels from the follow code:**
self.gud_up_proj_layer6 = self._make_gud_up_conv_layer(Simple_Gudi_UpConv_Block_Last_Layer, 64, 12, 228, 304)

**But then you only use the first 8 channels of this output from the code:**
gate1_wb_cmb = torch.abs(guidance.narrow(1, 0                   , self.out_feature))
        gate2_wb_cmb = torch.abs(guidance.narrow(1, 1 * self.out_feature, self.out_feature))
        gate3_wb_cmb = torch.abs(guidance.narrow(1, 2 * self.out_feature, self.out_feature))
        gate4_wb_cmb = torch.abs(guidance.narrow(1, 3 * self.out_feature, self.out_feature))
        gate5_wb_cmb = torch.abs(guidance.narrow(1, 4 * self.out_feature, self.out_feature))
        gate6_wb_cmb = torch.abs(guidance.narrow(1, 5 * self.out_feature, self.out_feature))
        gate7_wb_cmb = torch.abs(guidance.narrow(1, 6 * self.out_feature, self.out_feature))
        gate8_wb_cmb = torch.abs(guidance.narrow(1, 7 * self.out_feature, self.out_feature))
        
**Whether this is mistake ?** And the code should be :
self.gud_up_proj_layer6 = self._make_gud_up_conv_layer(Simple_Gudi_UpConv_Block_Last_Layer, 64, 8, 228, 304) ?

**Comment by XinJCheng** [comment]
Thanks for your attention, we have fixed it
