### ISSUE TITLE
is the cspn.py the final version descriped in the paper?

### ISSUE THREAD

**Issue by CHZhu940222** [XinJCheng/CSPN#2]
Is one propagation the same as the description in the paper 'Learning Depth with Convolutional Spatial
Propagation Network'?
what is the effect of max_of_4_tensor and eight_way_propagation?
thanks a lot!

**Comment by XinJCheng** [comment]
eight_way_propagation has been described in the paper, please check the Fig 2(b). 
max_of_4_tensor is something like an elemental max pooling layer
