### ISSUE TITLE
image input size

### ISSUE THREAD

**Issue by amaanda** [XinJCheng/CSPN#20]
is there a way to parse a larger image to the net? i am able to successfully load a png image in your code, and the depth info in an exr file, but i want to get a larger image as output. i tried changing the center crop and resize transform to twice the original parameters and I get the following error:

` File "./models/torch_resnet_cspn_nyu.py", line 270, in forward
    out = torch.cat((out, side_input), 1)
RuntimeError: invalid argument 0: Sizes of tensors must match except in dimension 1. Got 57 and 29 in dimension 2 at /pytorch/aten/src/THC/generic/THCTensorMath.cu:71
`

**Comment by XinJCheng** [comment]
For this nyudepth model, the input size should be same with cropped one.
