### ISSUE TITLE
cspn求和的卷积核应该在forward的时候创建

### ISSUE THREAD

**Issue by yellowYuga** [XinJCheng/CSPN#22]
self.weight = torch.ones(1, 8, 1, 1, 1).cuda()
cspn中的求和卷积如果在init过程构建的话，batch运行的时候，pytorch会提示不在一张卡上。
所以该weight应该在forward的过程中创建

**Comment by XinJCheng** [comment]
yes, this only works for one GPU training, thanks for your kindly reminder, I have updated it.
