### ISSUE TITLE
Did you up-sampling the depth when eval?

### ISSUE THREAD

**Issue by LINA-lln** [XinJCheng/CSPN#23]
Hi
Thank you very much for your contribution. I have a question when I read your paper. Did you up-sampling the depth to the original size when evaluation?

**Comment by XinJCheng** [comment]
thanks for your attention, As shown in the paper, the output size for the last layer in the network should be same with the input size.

**Comment by LINA-lln** [comment]
> thanks for your attention, As shown in the paper, the output size for the last layer in the network should be same with the input size.

And the output depth is directly evaluated according to the metrics with no up-sampling to 480*640 in NYUDv2 ? 
the same as kitti

**Comment by XinJCheng** [comment]
We first downsampled to half and then center-cropped to 304x228 as input, same with our baseline

**Comment by longyangqi** [comment]
Thank you for your code！
according to your `eval.py` , you directly compute the metrics on the cropped output depth and gt (eg. `304*228` for nyu),  without back to `640*480` ?
