### ISSUE TITLE
The code does not match the description of the paper

### ISSUE THREAD

**Issue by USTC-Keyanjie** [XinJCheng/CSPN#32]
Thanks for the awesome contribution!

When I read the code, I found that the code did not match the paper.

https://github.com/XinJCheng/CSPN/blob/24eff1296c282196f1c919714d8f32a9b0dbe7fb/cspn_pytorch/models/torch_resnet_cspn_nyu.py#L269

![image](https://user-images.githubusercontent.com/41223233/69033568-31411e00-0a1a-11ea-864b-c12accaa6b06.png)

According to the description of your paper, I think we should change

```
out = self.relu(self.bn1(self.conv1(x)))
out = torch.cat((out, side_input), 1)
```

to

```
x = self.relu(self.bn1(self.conv1(x)))
out = torch.cat((x, side_input), 1)
```
Looking forward to your reply!

**Comment by JUGGHM** [comment]
> Thanks for the awesome contribution!
> When I read the code, I found that the code did not match the paper.
> 
>   
>     
>       CSPN/cspn_pytorch/models/torch_resnet_cspn_nyu.py
>     
>     
>          Line 269
>       in
>       24eff12
>     
>     
>     
>     
> 
>         
>           
>            out = self.relu(self.bn1(self.conv1(x))) 
>         
>     
>   
> 
> 
> 
> According to the description of your paper, I think we should change
> out = self.relu(self.bn1(self.conv1(x)))
> out = torch.cat((out, side_input), 1)
> 
> to
> x = self.relu(self.bn1(self.conv1(x)))
> out = torch.cat((x, side_input), 1)
> 
> Looking forward to your reply!

I wonder is there any difference for the variable 

> out 

in two versions?

**Comment by USTC-Keyanjie** [comment]
The `out` indeed has no difference in two version. However, `x` has difference.

According to the description of the paper, `x` must pass the `conv`, `bn` and `relu` operations before entering the `shortcut` section.

In my opinion, the two version looks like
![image](https://user-images.githubusercontent.com/41223233/69117314-3bbaf080-0aca-11ea-9156-1dd61bda965a.png)
and
![image](https://user-images.githubusercontent.com/41223233/69117358-57be9200-0aca-11ea-922f-c3b9de37aa67.png)

**Comment by JUGGHM** [comment]
> The out indeed has no difference in two version. However, x has difference.
> According to the description of the paper, x must pass the conv, bn and relu operations before entering the shortcut section.
> In my opinion, the two version looks like
> 
> and

You're right

**Comment by XinJCheng** [comment]
Thanks for your attention and detailed review.
 Yes, this is a mistake, I will update it later.
Thanks
