### ISSUE TITLE
Tutorial

### ISSUE THREAD

**Issue by Z0org** [XinJCheng/CSPN#5]
Is it possible to get a short Tutorial that covers how to use the code and maybe how to train the Network?

**Comment by valdivj** [comment]
Yes I agree A short tutorial would be awesome. This looks promising.

**Comment by XinJCheng** [comment]
Thanks for your advice, I am still working on it. But I have some other higher priorities at hand. Really sorry for the slowly update.

**Comment by siyuanwu** [comment]
When you are not busy，I also hope that you can give a brief introduction how to use this network. Thank you.
