### ISSUE TITLE
Confuse about the way to get Affinity Matrix

### ISSUE THREAD

**Issue by ljm-ddm** [XinJCheng/CSPN#6]
Hello.
I have read your paper,and make some experiment about the 3DCSPN. But I didn't get good result.
I'm confused about the way to get Affinity Matrix in 3D Module (page 7).
Is use a simple 3d Conv and ReLU to get Affinity matrix or a multi-layer Conv model to get Affinity martix?
Thx

**Comment by XinJCheng** [comment]
we just used a simple 3D conv

**Comment by yellowYuga** [comment]
Hi.
 I get confused about 3dCSPN too.Did you get good result?

**Comment by ljm-ddm** [comment]
I have tried many methods, but did't got the result better than orign PSMNet.
